### ISSUE TITLE
Document the state of each magic dashboard

### ISSUE THREAD

**Issue by unflxw** [appsignal/public_config#46]
We should document how our magic dashboards actually work. For now, by adding a README for each dashboard -- ideally, this information would later be shown in the docs, as well as here (or instead of here)

Specifically, it's important to note:

- What is this metric? What does it measure? (Consider the metric's unit, whether it's cumulative or per-minute, etc)
  - Why do we emit this metric, why is it useful to measure this?
- What tag combinations are emitted for this metric? What do they mean?
  - Why do we emit these tag combinations for this metric, why are these combinations useful?
- When is this metric emitted? (What specific integration emits it, but also, under what conditions, at what point in the application's life cycle -- is it in response to an event, or as part of a minutely probe? is it _always_ emitted, or only when...?)

Let's add examples, links to the framework/library/database's documentation, to our own documentation, to the source code if needed -- it should be possible for someone to understand the purpose of these metrics without needing much familiarity with the piece of software being metered. 

To do
---

(spin separate issues if needed)

- [x] ~Remove dashboards which are unlikely to be generated anymore (i.e. the corresponding integration is deprecated)~
  - ... unless this would break something in the public dashboard updater logic? (do you happen to know @tombruijn?)
- [x] Add a README for each dashboard, documenting important information
  - [x] Erlang
  - [x] NGINX
  - [x] process_memory
  - [x] Sidekiq
- [x] Update the dashboards themselves with this information (i.e. add missing graph descriptions)
- [ ] #62
  - (add sub-tasks per dashboard if needed)

**Comment by tombruijn** [comment]
> * Remove dashboards which are unlikely to be generated anymore (i.e. the corresponding integration is deprecated)
>   * ... unless this would break something in the public dashboard updater logic? (do you happen to know @tombruijn?)

This should break nothing in the updater.

**Comment by unflxw** [comment]
@tombruijn 👍 to that -- feel free to update the to-do list.

That said, since this is a potential blocker for another team ([see Basecamp](https://3.basecamp.com/4738529/buckets/33238685/messages/6303796118#__recording_6316741914)) I think we should prioritise having _something_ that they can look at first, and getting to something that is _documentation ready_ later. (I'm thinking that screenshots and such can take time to make)

**Comment by unflxw** [comment]
Spun out #62 for turning the information in the READMEs into documentation updates, so this task can be closed.
